- source/creating_doc/doc_home.rst
- source/creating_doc/quickstart_rst.rst
- source/index.rst
Give people the bare minimum they need to know to write good RST
documents.
Not re-arranging anything yet, just looking for feedback on the new quickstart I wrote.
> feat: Add an opinionated quickstart for writing RST.

- source/documentors/doc_home.rst
Put the extra docs in a panel on the documentors home page
so that it looks a bit cleaner.
> docs: Move extra docs to a panel.

- catalog-info.yml
- openedx.yaml
Add metadata to get picked up by openedx releases and by backstage.
> docs: Add metadata files.

- source/documentors/decisions/0001-purpose-of-this-repo.rst
- source/documentors/decisions/index.rst
- source/documentors/index.rst
- source/index.rst
Capture the context and decsions made in order to create this repo and
to further invest time and effort into it.
> docs: Document the purpose of this repo.

- source/conf.py
- source/documentors/how-tos/add_a_doc_via_github.rst
- source/documentors/quickstarts/quick_start_add_doc.rst
- source/documentors/references/doc_checklist.rst
- source/documentors/references/doc_guidelines.rst
- source/educators/how-tos/add_course_creators.rst
- source/educators/how-tos/reusable_content/create_section.txt
- source/educators/how-tos/reusable_content/create_subsection.txt
- source/educators/how-tos/reusable_content/create_unit.txt
- source/educators/how-tos/reusable_content/schedule_course.txt
- source/educators/references/course_dates.rst
- source/educators/references/course_sections.rst
- source/educators/references/course_subsections.rst
- source/educators/references/course_units.rst
See commit messages for details.
> Merge feanil/fix_autosection_label into main

- source/other/getting_help.rst
* Update the slack link to use the redirect.
* Make the request for feedback a note.
> docs: Update the getting help page.

- source/_static/css/custom.css
- source/educators/quickstarts/build_a_course.rst
testing for build on RTD.  video not edited yet
> Build Course Quick Start Video

- source/developers/concepts/backend_layout_and_approach.rst
Add OEP and cookiecutter links relevant to backend layout and approach.
> feat: first pass at a real backend layout page

- source/other/feedback.rst
Switch to a form controlled by tCRIL so that we can add automation to
create github issues from submission to the form.
> docs: Update the feedback form.

- .github/workflows/upgrade-python-requirements.yml
Extra quotes were braking the build.
closes https://github.com/openedx/docs.openedx.org/issues/62
> build: Fix the requirements build.

- LICENSE
Adding our standard license for documentation.
> feature: adding cc license

- requirements/base.txt
- requirements/pip.txt
- sphinx-book-theme upgrade is minor fixes and enhancements.
- urllib3 has a minor bug fix not relevant to us.
- pip upgrade we just take.
> chore: Run `make upgrade`.

- source/documentors/concepts/content_types.rst
Also link to the framework we're using.
> docs: Add Quicktstarts to the list.

- source/developers/references/references_home.rst
- source/developers/references/tools_for_maintainers.rst
Outline the tools maintainers have at their disposal and the purposes of
those tools.
> docs: Document the tools available to maintainers.

- requirements/base.txt
- requirements/pip-tools.txt
- requirements/pip.txt
> run make upgrade

- source/developers/quickstarts/setup_a_backend_dev_environment.rst
@feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil @feanil
> fix: use clean install, not install. also headings.

- source/conf.py
> docs: expand banner text a bit

- source/developers/concepts/platform_overview.rst
> Fix tiny typo in "Platform Overview"

- source/translators/concepts/translation-process.rst
This PR adds translations-process.rst which contains a brief summary of the newly proposed translation process.
closes https://github.com/openedx/docs.openedx.org/issues/132
> feat: add translations process docs

- source/developers/how-tos/add-sphinx-docs-to-a-repo.rst
Distill the current recommendations into a quick how-to.
> docs: Add a doc for how to add sphinx to your project.

- requirements/base.in
- requirements/base.txt
- requirements/pip.txt
- source/conf.py
- source/developers/index.rst
- source/documentors/index.rst
- source/educators/how-tos/index.rst
- source/educators/index.rst
- source/educators/references/index.rst
- source/index.rst
- source/translators/index.rst
* sphinx-panels is no longer actively maintained
* the sphinx-panels documentation recommends using sphinx-design instead
resolves https://github.com/openedx/docs.openedx.org/issues/238
> refactor: sphinx-design cards, not sphinx-panels

- source/documentors/references/quick_reference_rst.rst
> Fix Quick Ref typos

- source/community/release_notes/maple.rst
@sarina here's my documentation update!
> Fix warning styling in Maple docs

- source/documentors/how-tos/add_a_doc_via_github.rst
- source/documentors/how-tos/reusable_content/create_github_account.txt
- source/documentors/how-tos/reusable_content/create_pull_request.txt
- source/documentors/how-tos/reusable_content/sign_agreement.txt
- source/documentors/how-tos/update_a_doc_via_github.rst
- source/documentors/quickstarts/quick_start_add_doc.rst
- source/documentors/quickstarts/update_doc_via_github.rst
- Move sidebar images inline
- Fix typos
- Update titles to specify "New" or "Existing" docs
> Update Documentors How-Tos & Quickstarts for Clarity

- source/community/release_notes/named_release_branches_and_tags.rst
> Update release lifecycle information

- source/community/release_notes/index.rst
- source/community/release_notes/named_release_branches_and_tags.rst
- source/community/release_notes/palm.rst
I'm creating release pages for Palm as documented on https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#5.-Update-the-documentation.
> docs: start the Palm release listing

- source/community/release_notes/olive.rst
* Changing some uppercase letters to lowercase.
@sarina, what do you think?
> Updating capitalization in release notes

- source/developers/how-tos/add-sphinx-docs-to-a-repo.rst
* Update the sphinx-book-theme config to match the updates needed for config changes in 1.0.0
> docs: Update add-sphinx-docs-to-a-repo.rst

- source/developers/how-tos/ongoing-maintainers-tasks.rst
PR onto the branch to capture some agree to standards for managing PRs.
> Maintainer docs: Managing PRs

- .github/workflows/upgrade-python-requirements.yml
Update this to run on Sundays so the PRs are ready to view on Monday when I usually go through maintenance work.
> build: Update upgrade-python-requirements.yml cron

- source/developers/concepts/platform_overview.rst
Embed the one video but then link to the whole playlist at the bottom.
> docs: Add a link to a arch intro video.

- source/developers/references/internal_data_formats/tracking_log_event_list.rst
- source/developers/references/internal_data_formats/tracking_logs/student_event_types.rst
Closes #342 and is probably ok to go as is, but there are open questions here: https://github.com/openedx/docs.openedx.org/pull/321#discussion_r1231100714
> Add Palm forum tracking events

- source/educators/how-tos/add_checkbox.rst
- source/educators/how-tos/add_content_iframe.rst
- source/educators/how-tos/add_course_creators.rst
- source/educators/how-tos/add_course_page.rst
- source/educators/how-tos/add_course_updates.rst
- source/educators/how-tos/add_dropdown.rst
- source/educators/how-tos/add_image.rst
- source/educators/how-tos/add_multiple_choice.rst
- source/educators/how-tos/add_numerical_input.rst
- source/educators/how-tos/add_text_input.rst
- source/educators/how-tos/add_transcript_other_language.rst
- source/educators/how-tos/add_video_quiz.rst
- source/educators/how-tos/add_written_content.rst
- source/educators/how-tos/course_reruns.rst
- source/educators/how-tos/create_course.rst
- source/educators/how-tos/create_course_about_page.rst
- source/educators/how-tos/create_video.rst
- source/educators/how-tos/import_scorm_content.rst
- source/educators/how-tos/importing_exporting.rst
- source/educators/how-tos/index.rst
- source/educators/how-tos/leveraging_libraries.rst
- source/educators/how-tos/manage_files.rst
- source/educators/how-tos/set_up_certificates.rst
- source/educators/how-tos/set_up_content_groups.rst
- source/educators/how-tos/set_up_prerequisites.rst
- source/educators/how-tos/using_lti.rst
- source/site_ops/quickstarts/index.rst
Add the how-to videos from the [Instructional Series for Course Authors playlist](https://www.youtube.com/playlist?list=PL87xhvJSz2W5AhGcra8ojmxqIGSUetiZY).
> docs: add how-to videos

- source/developers/how-tos/enable-translations-new-repo.rst
- source/developers/how-tos/maintain-translations-in-your-repo.rst
@OmarIthawi @brian-smith-tcril : here's the start of two How-To articles explaining how to enable translations on a new repo and how to maintain translations on an existing repo. Feel free to PR into this branch and add new sections as needed.
> docs: Add translations how-to articles

- source/translators/quickstarts/start-translating-openedx.rst
Adding a section called "Useful Links"
> Update start-translating-openedx.rst file

- source/translators/quickstarts/start-translating-openedx.rst
Adjusting typos under section "Translate a string".
> AdjustingTypos

- source/translators/quickstarts/start-translating-openedx.rst
Adjusting bold type in 2 steps within "Finding a string to translate" section and adjusting the numbered list to avoid duplicates (two number 1, steps 1 & 2).
> AdjustingFindingaStringToTranslate.rst

- source/translators/quickstarts/start-translating-openedx.rst
Adding link to Useful Links section.
> AddingLink.rst

- source/community/release_notes/named_release_branches_and_tags.rst
Add a link to the release schedule
> docs: Update named_release_branches_and_tags.rst

- source/developers/how-tos/maintain-translations-in-your-repo.rst
Add translations maintenance document with few common problems.
> docs: add maintain-translations-in-your-repo.rst | FC-0012

- source/translators/how-tos/how-to-join-a-translation-team.rst
- source/translators/quickstarts/start-translating-openedx.rst
> docs: use new project links | FC-0012

- source/community/release_notes/redwood/dev_op_release_notes.rst
- source/community/release_notes/redwood/studio_facelift.rst
https://docsopenedxorg--521.org.readthedocs.build/en/521/community/release_notes/redwood/dev_op_release_notes.html#flags-specific-to-the-new-course-authoring-mfe
> docs: Add complete course authoring MFE flags to Redwood release notes

- source/community/release_notes/redwood/dev_op_release_notes.rst
This PR update the link to the Aspects Configuration documentation.
> docs: link update to documentation

- source/educators/how-tos/Create_flat_taxonomy_by_uploading_CSV.rst
- source/educators/how-tos/index.rst
This change adds a Content Tagging how-to showing users the process for creating a flat taxonomy by uploading a CSV
> Add Create_flat_taxonomy_by_uploading_CSV.rst how-to

- source/developers/concepts/backend_layout_and_approach.rst
Intended available path link to access the page.
> docs(backend_layout_and_approach): link Django app patterns

- .github/ISSUE_TEMPLATE/config.yml
See https://github.com/openedx/axim-engineering/blob/main/.github/ISSUE_TEMPLATE/config.yml
> Add issue template configuration file

- .github/workflows/upgrade-python-requirements.yml
@feanil is this the right syntax?
> build: Update reviewers in python-requirements wkflow

- source/documentors/references/doc_media_accessibility.rst
This PR migrates the media accessibility reference from the edX repositories to the Open edX documentors section.
> FC-0068 docs: add media accessibility reference

- source/educators/concepts/advanced_features/cohorts_overview.rst
- source/educators/concepts/advanced_features/content_experiments_overview.rst
- source/educators/concepts/advanced_features/group_configurations.rst
- source/educators/concepts/advanced_features/guidlines_modifying_group_configuration.rst
- source/educators/concepts/advanced_features/offering_differentiated_content.rst
This PR contains 5 concept documents reviewed for the educators' documentation project.
> FC-0068 docs: educators documents review 1-edunext

- source/educators/how-tos/content-tagging-how-tos/build_taxonomy_using_template.rst
- source/educators/how-tos/course_development/exercise_tools/Manage_ORA_Assignment.rst
cleaning up for build_taxonomy_using_template.rst
> cleaning up for howtos

- source/educators/quickstarts/build_a_course.rst
> fc-0068 docs: cleaning up for build_a_course

- source/community/release_notes/redwood/sidebar_nav.rst
- source/community/release_notes/sumac/default_sidebar_nav.rst
- source/community/release_notes/sumac/feature_release_notes.rst
* https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4657872899/Sidebar+Navigation
> Add Sumac relnote for Default Sidebar Nav

- source/educators/how-tos/course_development/set_course_highlights.rst
cleaning up for set_course_highlights.rst
> cleaning up for how-tos4

- source/community/release_notes/index.rst
- source/community/release_notes/old_releases.rst
- source/community/release_notes/sumac.rst
- source/community/release_notes/teak/aspects_updates.rst
- source/community/release_notes/teak/design_tokens.rst
- source/community/release_notes/teak/feature_release_notes.rst
- source/community/release_notes/teak/libraries_unit_support.rst
- source/community/release_notes/teak/stay_up_to_date.rst
- source/community/release_notes/ulmo.rst
- source/community/release_notes/ulmo/dev_op_release_notes.rst
- source/community/release_notes/ulmo/feature_release_notes.rst
- source/index.rst
@feoh fyi - this should be merged to make the navigation work right once Sumac is released.
https://docsopenedxorg--673.org.readthedocs.build/en/673/
https://docsopenedxorg--673.org.readthedocs.build/en/673/community/release_notes/index.html
> Make Sumac the Current Release

- source/community/release_notes/sumac/dev_op_release_notes.rst
Discuss post as a reference: https://discuss.openedx.org/t/git-checkout-open-release-sumac-master/14220
> fix: set a correct sumac cut-off date

- source/community/release_notes/sumac/aspects_comp_dashboard.rst
- source/community/release_notes/sumac/dev_op_release_notes.rst
> Update Aspects links in Sumac release notes

- source/educators/how-tos/allow_anonymous_discussions.rst
- source/educators/how-tos/communication/setup_cohorted_discussions.rst
- source/educators/how-tos/course_development/hide_subsections.rst
- source/educators/how-tos/create_course.rst
- source/educators/how-tos/create_course_about_page.rst
- source/educators/how-tos/create_subsection.rst
- source/educators/how-tos/data/manage_course_grades.rst
- source/educators/how-tos/update_rerun_course.rst
- source/educators/references/resources_for_course_teams.rst
- source/educators/references/resources_for_open_edx.rst
- source/educators/references/reusable_references/course_highlight_message_text.rst
adding see also table for course_highlight_message_text.rst
> adding seealso table 3

- source/educators/concepts/instructional_design/id_course_dev_process_overview.rst
- source/educators/references/data/understanding_progress_page.rst
Safe spelling and syntax updates
> Spelling and syntax updates

- source/educators/how-tos/advanced_features/add_content_experiments_olx.rst
- source/educators/how-tos/advanced_features/test_content_experiments.rst
- source/educators/how-tos/course_development/add_components_library.rst
- source/educators/how-tos/course_development/create_library.rst
- source/educators/how-tos/course_development/delete_library.rst
- source/educators/how-tos/course_development/edit_components_library.rst
- source/educators/how-tos/course_development/edit_library.rst
- source/educators/how-tos/course_development/exercise_tools/CreateORAAssignment.rst
- source/educators/how-tos/course_development/view_content_legacy_library.rst
- source/educators/navigation/content_creation_management.rst
This PR modifies a series of how-to documents migrated from the legacy repositories to the educators' documentation.
> FC-0068 docs: How-to cleaning by edunext #8

- source/educators/references/data/student_profile_report.rst
Per https://github.com/openedx/docs.openedx.org/issues/647 I'm attempting to clarify the columns listed in this doc a bit more and correct a couple of points that I _believe_ are currently wrong.
> docs: Update student profile report columns

- source/educators/how-tos/add_course_page.rst
- source/educators/how-tos/course_development/add_textbooks.rst
- source/educators/how-tos/course_development/create_course_wiki.rst
- source/educators/how-tos/course_development/exercise_tools/create_full_screen_image.rst
- source/educators/how-tos/course_development/text_components/add_image.rst
- source/educators/how-tos/course_development/text_components/create_text_component.rst
- source/educators/how-tos/course_development/text_components/format_image.rst
- source/educators/how-tos/course_development/text_components/paste_without_formatting.rst
- source/educators/how-tos/course_development/text_components/work_with_html.rst
- source/educators/how-tos/course_development/text_components/work_with_latex.rst
- source/educators/how-tos/manage_files.rst
- source/educators/navigation/content_creation_management.rst
This PR modifies how-tos documents migrated from the legacy repositories to the educators' documentation.
> FC-0068 docs: how-tos reviewed by 17 edunext

- source/educators/how-tos/add_multiple_choice.rst
- source/educators/how-tos/content-tagging-how-tos/build_taxonomy_using_template.rst
- source/educators/how-tos/reusable_content/add_multiple_choice.txt
- source/educators/references/course_pacing.rst
- source/educators/references/student_management/enrollment_requirements.rst
fixing see also table links for course_pacing.rst
> Fixing see also table links 

- source/developers/concepts/hooks_extension_framework.rst
This PR updates the link to the edx-django-utils, the tags, and the maintenance chart of this article.
> [FC-0074] docs: update hooks_extension_framework

- source/translators/concepts/working-with-html.rst
Based on community feedback
build: https://docsopenedxorg--896.org.readthedocs.build/en/896/translators/concepts/working-with-html.html
> Add HTML Beginners Link to HTML Translators page

- source/educators/how-tos/add_custom_css_or_javascript_code_to_a_course.rst
- source/educators/navigation/advanced_features.rst
Add Educator documentation OEP-15. 
Ref: https://github.com/openedx/open-edx-proposals/issues/671
private-ref: https://tasks.opencraft.com/browse/BB-9571
> docs: Add documentation for course-wide CSS and JS

- source/community/concepts/what_is_the_roadmap.rst
- source/community/how-tos/read_the_roadmap.rst
- source/community/index.rst
- source/community/release_notes/teak/stay_up_to_date.rst
- source/educators/references/resources_for_course_teams.rst
- source/links.txt
Transcribes https://docs.google.com/document/d/1uuik8ZbDgzEdrC_G46fev3HZe0OVFms5Jl_xlM2aYos/edit?tab=t.0 (finalized) and https://docs.google.com/document/d/1UmrZFyc2h60qC8C3lVk5f6El2ReBVY01QSwOSUMuLqk/edit?tab=t.0 (finalized)
> Add Community how to and concept guides on the Product Roadmap

- source/educators/how-tos/course_development/social_sharing.rst
- source/educators/references/course_development/about_page.rst
- **Add missing Maintenance Table**
- **Add missing docs referenced in fea-publisher**
> add missing docs feapub

- source/educators/navigation/content_creation_management.rst
- source/educators/olx/about/overview.rst
- source/educators/olx/about/short-description.rst
- source/educators/olx/assets/assets.rst
- source/educators/olx/components/discussion-components.rst
- source/educators/olx/components/html-components.rst
- source/educators/olx/components/problem-components.rst
- source/educators/olx/components/video-components.rst
- source/educators/olx/content-experiments/content_experiments_test_olx.rst
- source/educators/olx/directory-structure.rst
- source/educators/olx/example-course/insider-course-xml.rst
- source/educators/olx/example-course/insider-structure.rst
- source/educators/olx/front_matter/read_me.rst
- source/educators/olx/getting-started.rst
- source/educators/olx/organizing-course/course-structure-overview.rst
- source/educators/olx/organizing-course/course-xml-file.rst
- source/educators/olx/pages/pages.rst
- source/educators/olx/policies/assets-policy.rst
- source/educators/olx/policies/course.rst
- source/educators/olx/policies/grading.rst
- source/educators/olx/problem-xml/symbolic_response.rst
- source/educators/olx/studio-example/index.rst
- source/educators/olx/studio-example/manual-testing-structure.rst
- source/educators/olx/what-is-olx.rst
- source/educators/quickstarts/build_a_course.rst
Addresses https://github.com/openedx/docs.openedx.org/issues/826
> Add seealso tables for OLX pages

- source/community/release_notes/teak/dev_op_release_notes.rst
[$517](https://github.com/openedx/wg-build-test-release/issues/517)
Open edX Teak release notes - incomplete first cut.
Currently just Deprecations and Operator notes, which is pretty much all that's on the Teak release notes page. Time to beat the bushes for more :)
> Open edX Teak release notes - incomplete first cut

- source/community/release_notes/redwood/sidebar_nav.rst
- source/community/release_notes/sumac/default_sidebar_nav.rst
- source/community/release_notes/sumac/dev_op_release_notes.rst
This pull request updates the following release notes to notify users that if they are experiencing formatting issues with the sidebar navigation, there is a known cause and fix for this issue that is detailed in the updated text:
- Redwood Product Release Notes
- Sumac Product Release Notes
- Sumac Operator and Dev Release Notes
Please let me know if you have any questions.
> Update release notes for Redwood and Sumac to include fix for sidebar nav breaking change

- source/developers/references/internal_data_formats/data_references/sql_schema.rst
- source/educators/concepts/exercise_tools/randomized_content.rst
- source/educators/concepts/instructional_design/libraries.rst
- source/educators/how-tos/course_development/add_components_library.rst
- source/educators/how-tos/course_development/create_and_edit_content_in_a_library.rst
- source/educators/how-tos/course_development/create_and_edit_units_in_a_library.rst
- source/educators/how-tos/course_development/create_library.rst
- source/educators/how-tos/course_development/create_new_library.rst
- source/educators/how-tos/course_development/delete_library.rst
- source/educators/how-tos/course_development/edit_components_library.rst
- source/educators/how-tos/course_development/edit_library.rst
- source/educators/how-tos/course_development/exercise_tools/use_randomized_content_blocks.rst
- source/educators/how-tos/course_development/export_import_library.rst
- source/educators/how-tos/course_development/library_access.rst
- source/educators/how-tos/course_development/navigate_library_homepage.rst
- source/educators/how-tos/course_development/use_content_sidebars_to_manage_content.rst
- source/educators/how-tos/course_development/view_content_legacy_library.rst
- source/educators/navigation/content_creation_management.rst
- source/glossary.rst
Replaces #1249 due to me not doing Git properly.
- Create a new page for Create Library instructions and mark old Create Library page as legacy
- Update all Legacy Libraries refs to say Legacy
- Add warnings to Randomized Content pages that they need to be updated for new-style Libraries
> Update Legacy Libraries docs

- source/developers/quickstarts/so_you_want_to_contribute.rst
I think I got the .rst syntax right.
> docs: link to the CLA

- source/developers/concepts/oep58.rst
- source/translators/how-tos/how-to-fix-translation-errors.rst
- source/translators/how-tos/how-to-join-a-review-team.rst
- source/translators/how-tos/how-to-join-a-translation-team.rst
- source/translators/how-tos/how-to-request-a-new-language.rst
- source/translators/quickstarts/start-translating-openedx.rst
> Update Request a New Language instructions for translators
