openedx/docs.openedx.org

- source/educators/how-tos/reusable_content/create_course.txt
The course key format is `course-v1:ORG+COURSE+RUN`.
The docs were missing the `-v1` suffix.
Side note: The new docs are looking real snazzy 😄
> docs: fix course URL structure in course creation how-to

- source/documentors/quickstarts/first_documentation_pr.rst
- source/index.rst
- source/other/getting_help.rst
I could imagine using this multiple times so making it a separate page that we reference.
> Add a general getting help page

- source/conf.py
Added a link to the cookie policy in the footer of the navbar.
closes https://github.com/openedx/docs.openedx.org/issues/31
> docs: Add a link to the cookie policy for this site.

- source/_static/css/custom.css
This commits add a CSS role, so that when html lang is ar. It
would set text-align to inherit, instaed of the deafult which
is left. See PR for screenshots
Please noteice the empty space between or before the text.
> fix: text style for Arabic lang/RTL

- source/conf.py
- source/developers/references/references_home.rst
We can make more complex connections in the future but at the very least
link the repo docs to the core developer reference docs.
> docs: Connect the DoneXBlock docs to the root site.

- catalog-info.yaml
Remove the source code link because backstage automatically has that.
Instead add a link to the deployed site.
> docs: Update catalog-info.yaml links list.

- source/developers/quickstarts/setup_an_mfe_dev_environment.rst
- source/developers/quickstarts/setup_an_plugin_dev_environment.rst
Adding plugin developer quickstarts + coming soon messages that will be linked in the developer quickstart docs.
> docs: add developer quickstarts coming soon

- Makefile
It's not gauranteed that people will have pip-sync by default in their
environments so install pip-tools as a part of the requirements update
process.
> build: Update the `requirements` target.

- source/index.rst
* Remove the panel for the persona homes since we have buttons for each
of them in their own panels.
* Make the wording more consintent for the different sections across
personas.
> docs: Update the docs homepage.

- source/_static/css/custom.css
This commit does two things:
- for pre tag (the tag which is used to show snippet) it force
it to be aligned to left. (Since all code sippet are in English)
- For ::after of a tag, in table of content: it overides the
content, from '>' to '<'.
>  CSS styles for Arabic 

- .github/workflows/upgrade-python-requirements.yml
Workflow scripts are defined in the .github repo under workflow-templates. This commit copies the changes from that workflow into this repo.
@feanil 
heads up to @kdmccormick and @mariajgrimaldi - to fix this issue copy the canonical workflow into the .github/workflows directory (be sure to preserve any customizations you may have made)
> build: use canonical upgrade-python workflow

- .github/workflows/upgrade-python-requirements.yml
see https://github.com/openedx/docs.openedx.org/pull/134
see here: https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization#creating-a-starter-workflow
> If you need to refer to a repository's default branch, you can use the $default-branch placeholder. When a workflow is created the placeholder will be automatically replaced with the name of the repository's default branch.
Reading between the lines, this indicates that `$default-branch` is a template feature, not a workflow file feature. The `$default-branch` gets read and interpolated at the time the template gets turned over into a workflow file, i.e. when the template gets used to create a new workflow.
> fix: github workflow main/$default-branch distinction

- source/developers/quickstarts/first_openedx_pr.rst
Turns out they basically are already fine for linux so we don't need to
do anything other than make it clear that the instructions should work
on linux as well.
closes https://github.com/openedx/docs.openedx.org/issues/117
> docs: Make the first PR instructions good for linux as well.

- source/developers/concepts/platform_overview.rst
- source/developers/index.rst
Provide just enough context that new people can get a lay of the land
and can orient themselves.
> docs: Add a super high-level overview of the platform.

- source/_templates/layout.html
This fixes part of #126, by just enabling tx to detect language
ref: https://docs.transifex.com/live/api#language-detection
> feat: enable tx detectlang

- source/conf.py
- source/index.rst
Add the intersphinx mapping to make it easier to reference specific OEPs
easier.
Unfortunately we can't put an intersphinx mapping into a toctree so we
just put a link to the subproject instead.
> docs: Add the openedx-proposals sub-project.

- source/developers/how-tos/add-sphinx-docs-to-a-repo.rst
This PR fixes the favicon path for the add sphinx docs how-to.
Try entering both URL(s). The current won't work without changing `openedx` for `open-edx`.
> fix: use correct logo path for sphinx favicon configuration

- source/developers/how-tos/switch-to-the-sphinx-book-theme.rst
With https://github.com/openedx/edx-sphinx-theme/issues/184 we deprecate
the edx-sphinx-theme so provide some docs for how people can migrate to
the new theme.
> docs: Add a basic how-to for switching to the new theme.

- requirements/base.in
- requirements/base.txt
- requirements/pip.txt
- source/community/release_notes/old_releases.rst
- source/conf.py
We want to be able to dynamically point to the latest release. This allows us to have one url for "latest.html" which we can point to wherever we need.
- feat: Add a redirect extension.
- chore: Run `make upgrade`
> Make a dynamic link for the latest release

- source/conf.py
- source/site_ops/index.rst
We haven't had time to migrate these yet so link to the existing docs
for now.
> docs: Add a link to the old operators notes.

- source/community/release_notes/named_release_branches_and_tags.rst
`open-release/olive.2` was released today. This adds the details to the table of release tags.
> Add Olive.2 to list of release tags.

- source/_static/css/custom.css
The button is falling back to a sphinx-design color that is too light
compared to the white background to be WCAG compliant.  Explicitly set
the color for those buttons to be the same as the other links on the
page which are WCAG AA compliant with a ration of 5.13
> fix: Fix the button color contrast.

- source/developers/concepts/platform_overview.rst
Issue: https://github.com/openedx/edx-platform/issues/31659
Update references in plugin docs for more clarity in how to start creating a plugin
> docs: update references in plugin docs

- source/developers/how-tos/add-sphinx-docs-to-a-repo.rst
Visit https://docs.openedx.org/en/latest/developers/how-tos/add-sphinx-docs-to-a-repo.html?highlight=diataxis and notice links to Diataxis are broken
View fixed in https://docsopenedxorg--276.org.readthedocs.build/en/276/developers/how-tos/add-sphinx-docs-to-a-repo.html
> fix: fully qualify Diataxis URL

- source/documentors/quickstarts/first_documentation_pr.rst
- source/documentors/references/quick_reference_rst.rst
- source/documentors/references/rst_samples/headings.txt
- source/documentors/references/rst_samples/nested_lists.txt
Per https://sublime-and-sphinx-guide.readthedocs.io/en/latest/lists.html,
nesting inside ordered lists requires 3 spaces and nesting inside
unordered lists requires 2 spaces.
> fix: RST Quick Reference clarification on list indentation

- source/documentors/references/rst_samples/headings.txt
It's not ideal to be nested this deeply, but it's already the case in some of the release notes
(https://github.com/openedx/docs.openedx.org/pull/311) so we should have a recommendation for it.
I chose `~` because it works with the mneumonic:
four lines (`#`), three lines (`*`), two lines (`=`), one line (`-`) if you consider a tilde to have "zero" lines.
> docs: recommend tilde (`~~~~`) for heading 5 underline

- source/documentors/references/quick_reference_rst.rst
This trick helped me remember the heading levels,
so maybe it'll help others too?
From: https://docsopenedxorg--318.org.readthedocs.build/en/318/documentors/references/quick_reference_rst.html#headings
> docs: describe number-of-lines mnemonic for heading levels

- source/developers/how-tos/use-python-coverage-comment.rst
This is meant to be offered up as a possible alternative to using codecov.
https://github.com/edx/edx-arch-experiments/issues/255
> feat: Add a How-To on setting up python-coverage-comment.

- source/translators/index.rst
These two sections have more articles that aren't listed in the small
tiles. So add a link to the index page for these sections.
> docs: Add links to the index for concepts and how-tos.

- source/conf.py
- source/developers/references/index.rst
Relies on changes here: https://github.com/openedx/openedx-oars/pull/55 and the subsequent renaming of that repo.
> docs: Update configuration for the oars repo name changes

- source/developers/how-tos/add-sphinx-docs-to-a-repo.rst
`reference` -> `references` - Everything else is plural, and we use `references` in this repo, so the fact that it wasn't plural here was probably an oversight.
> docs: Update add-sphinx-docs-to-a-repo.rst

- source/community/release_notes/named_release_branches_and_tags.rst
This adds the new Palm.2 release that was tagged today to the list of releases.
It also adds Olive.4, which we forgot to add at the time it was tagged.
> docs: add Palm.2 to list of releases

- source/community/release_notes/palm.rst
@sambapete pointed out this language in the release notes.
> The visual problem editor is an update to the Course Authoring Micro-frontend first released in Olive and is enabled by default in Palm. To enable the Visual Problem Editor, add the waffle flag new_core_editors.use_new_problem_editor and set the value to “Yes” for all users.
I think this is saying that the Course Authoring MFE is enabled by default in Palm, but when I first read it I thought it was saying that the Visual Problem Editor is default in Palm.
Here's a small update that I think would make it clearer what the current state of the editor is.
> docs: clarify that visual problem editor is not the default in Palm

- source/developers/how-tos/ongoing-maintainers-tasks.rst
- source/developers/index.rst
- source/developers/maintainers_home.rst
Hade a single page that can serve as a hub for resources for
maintainers.  The content is still a part of the general developer space
but we're using a new special home page to collect the items that are
specifically relevant to maintainers so it's easier to find.
> docs: Add a maintainers homepage.

- source/developers/quickstarts/first_openedx_pr.rst
Under the section, `Install Tutor Nightly` update the command `tutor dev quickstart` to `tutor dev launch` to configure and provision an Open edX instance. `quickstart` is not listed as one of the options commands for `tutor dev`.
**Navigation:**
```
|--- Quickstarts
|--- Developers: Contribute to Open edX
|--- Quick Start: First Open edX Pull Request
|--- #Section: Installing Tutor Nightly
```
Here is the documentation [link](https://docs.openedx.org/en/latest/developers/quickstarts/first_openedx_pr.html#installing-tutor-nightly). 
**Problem:**
When following the tutorial I encountered a blocker in executing one of the provided commands: `tutor dev quickstart`.
**Expected:**
An interactive session to configure and provision an Open edX instance. 
**Actual:**
The following terminal output …
> docs: Update 'install tutor nightly' command.

- source/developers/how-tos/enable-translations-new-repo.rst
document the new translation workflow for Python Repo.
I'll be filling the other sections in upcoming PRs.
For now the controversial part is whether we should be recommending `i18n_tool extract` or use `django-admin.py makemessages`. My memory isn't helping me to determine which does what, so I'll be asking for help from @shadinaif and of course @sarina who have used both a ton.
Preview the file here: https://github.com/Zeit-Labs/docs.openedx.org/blob/mfe-atals-docs/source/developers/how-tos/enable-translations-new-repo.rst
This pull request is open against a parent one that'll be merged later:
- https://github.com/openedx/docs.openedx.org/pull/363
----
This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation …
> docs: add the Python Repo section into OEP-58 docs

- source/developers/how-tos/enable-translations-new-repo.rst
Combines the previously closed requests into a single PR:
- #383 
- #384 
- #382 
- Preview this document from following link: [how-tos/enable-translations-new-repo.rst](https://github.com/Zeit-Labs/docs.openedx.org/blob/oep58-docs/source/developers/how-tos/enable-translations-new-repo.rst)
This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
> docs: complete enable-translations-new-repo.rst MFE and microservice sections

- source/_templates/primary_sidebar_end.html
- source/community/index.rst
- source/community/security_policy/index.rst
The Open edX security policy was updated as part of https://github.com/openedx/.github/pull/82. The policy should also be part of the documentation to ensure that any users of the Open edX platform are aware of where to disclose security vulnerabilities.
> docs: add security policy to community section

- source/community/release_notes/index.rst
- source/community/release_notes/named_release_branches_and_tags.rst
- source/community/release_notes/quince.rst
Adding Quince to docs regarding the [Release process](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#5c.-Add-the-latest-release-to-the-main-docs-site).
> docs: start the Quince release listing

- source/developers/how-tos/get-ready-for-python-dev.rst
We currently have "Getting Started" instructions in each repo's README, but they're terse and often out of date. By moving them to a central place, we can instead link to those docs and reduce our maintenance burden.
This would also involve updating OEP-55 to specify a link to this doc page rather than [suggesting an inlined Getting Started section](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0003-readme-specification.html).
> docs: Add how-to for Python development (virtualenvs, make test)

- source/translators/quickstarts/start-translating-openedx.rst
Editing "Before you Start" section, adjusting email link and trying to make the difference between edXplatform and website clearer.
Also, adding punctuation for other sections.
> EditingBeforeYouStartSection.rst

- source/developers/references/developer_guide/links.rst
- source/developers/references/developer_guide/process/code-considerations.rst
- source/developers/references/developer_guide/process/overview.rst
Addresses #401
Rendered: https://docsopenedxorg--424.org.readthedocs.build/en/424/developers/references/developer_guide/process/code-considerations.html
> Update Dev Guide > Code Considerations file

- source/developers/index.rst
Pull these up to the developer home page to get to them faster.
> docs: Point to the published edx-platform bocs.

- source/conf.py
- source/developers/references/glossary.rst
- source/developers/references/index.rst
Add pointers to the XBlock repo docs in the References section as well as a reference in the glossary
> build: Add XBlock docs references

- source/community/release_notes/named_release_branches_and_tags.rst
Adds the new Palm.4 release that was tagged 16/11 to the list of releases.
> docs: add Palm.4 to list of releases

- source/community/release_notes/named_release_branches_and_tags.rst
Quince and Palm had the wrong heading underline
(~ instead of =) so they were rending a level above the named releases.
> fix: headings on named releases page

- source/community/release_notes/index.rst
- source/community/release_notes/named_release_branches_and_tags.rst
- source/community/release_notes/old_releases.rst
- source/conf.py
- source/index.rst
Quince.1 release update. This points latest release to Quince.
See: https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#4b.-Make-the-new-release-notes-the-%E2%80%9Clatest%E2%80%9D
> chore: update docs for new Quince.1 release

- source/documentors/references/doc_templates.rst
In https://docs.openedx.org/en/latest/documentors/references/doc_templates.html#create-a-how-to the seealso directive says to use :ref:, however, :doc: is the way to reference a whole document. Added an example and comments to clarify when to use which.
> Clarify how to use :ref: vs :doc: in our templates

- source/developers/how-tos/enable-translations-new-repo.rst
Documents JS translations feature in the platform:
- https://github.com/openedx/edx-platform/pull/33698
Preview link:
- https://github.com/Zeit-Labs/docs.openedx.org/blob/xblock_js/source/developers/how-tos/enable-translations-new-repo.rst#configuration
> docs: XBlock JavaScript translations OEP-58

- source/community/release_notes/named_release_branches_and_tags.rst
Adds the new Quince.2 release that was tagged 2024-02-09 to the list of releases.
> docs: add Quince.2 to list of releases

- source/developers/how-tos/enable-translations-new-repo.rst
This option will be no longer needed for new repositories after the following PR is merged:
- https://github.com/openedx/frontend-template-application/pull/728
> docs: remove OPENEDX_ATLAS_PULL | FC-0012

- source/translators/how-tos/how-to-fix-translation-errors.rst
- source/translators/how-tos/how-to-request-a-new-language.rst
Docs for policy and process for adding new language.
> docs: add new language and fix translation errors | FC-0012

- source/community/release_notes/named_release_branches_and_tags.rst
Adds the new Quince.3 release that was tagged 2024-04-09 to the list of releases.
Localtion: `docs.openedx.org/build/html/community/release_notes/named_release_branches_and_tags.html`
> docs: add Quince.3 to list of releases

- source/site_ops/how-tos/add-waffle-flag-for-user.rst
For [TNL-11198](https://2u-internal.atlassian.net/browse/TNL-11198), the Open edX docs need to contain a page on how to enable a waffle flag for a user. Private details from [this doc](https://2u-internal.atlassian.net/wiki/spaces/TNL/pages/653623584/How+to+Enable+a+Waffle+Flag+for+a+User) have been removed.
> Add Open edX support doc for enabling waffle flags

- source/community/release_notes/index.rst
- source/community/release_notes/named_release_branches_and_tags.rst
- source/community/release_notes/redwood.rst
Adding Redwood to docs regarding the [Release process](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#5c.-Add-the-latest-release-to-the-main-docs-site).
> docs: start the Redwood release listing

- source/developers/quickstarts/first_openedx_pr.rst
Enabling the arm64 plugin will break Tutor in latest version. Keep it disabled even on M1 machines.
> docs: Remove arm64 section and add PR push auth solution

- source/educators/migration_wip/15_releasing_course/export_import_course.rst
- source/educators/migration_wip/links/links.rst
I was reading this section and noticed some issues.
- images are updated
- content changed a bit for better readability
- 1 outdated/redirected link fixed.
> fix: Import Export course content

- source/community/release_notes/index.rst
- source/community/release_notes/old_releases.rst
- source/community/release_notes/redwood.rst
- source/community/release_notes/sumac.rst
- source/index.rst
Necessary changes for the OpenEdX Redwood release.
Fixes: https://github.com/openedx/wg-build-test-release/issues/377
Built version on [ReadTheDocs](https://docsopenedxorg--507.org.readthedocs.build/en/507/)
---
Replaces https://github.com/openedx/docs.openedx.org/pull/503 which died due to a Github branching mishap.
> docs: Redwood release notes first cut.

- source/community/release_notes/redwood.rst
The Beta Course Search enablement documentation was listed under
"other operator changes". It is now within the "Learner and Instructor
Experiences" section, as it is related to a key Instructor feature.
> Move Course Search section within Redwood Release Notes

- source/community/release_notes/named_release_branches_and_tags.rst
- source/conf.py
Redwood.1 release update. This points latest release to Redwood.
See: https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#4b.-Make-the-new-release-notes-the-%E2%80%9Clatest%E2%80%9D
> chore: update docs for new Redwood.1 release

- source/community/release_notes/redwood/aspects.rst
This PR updates different links in the release notes to direct them to the Aspects documentation.
> docs: Update documentation links in release note

- source/community/release_notes/quince/copy_paste_a.rst
- source/community/release_notes/quince/copy_paste_b.rst
- source/community/release_notes/quince/demox_course.rst
- source/community/release_notes/quince/feature_roundup.rst
- source/community/release_notes/quince/woocommerce.rst
In order to match the way we did Redwood posts, append (Quince) to the title of Quince blog posts.
> Add (Quince) to titles of Quince blog posts

- source/community/release_notes/quince/woocommerce.rst
Link to docs.openedx.org, not the root docs in the repo
> Add better link to WooCommerce docs in Quince post

- source/community/release_notes/redwood/aspects.rst
- source/community/release_notes/redwood/content_tagging.rst
- source/community/release_notes/redwood/course_search.rst
- source/community/release_notes/redwood/potpourri.rst
- source/community/release_notes/redwood/sidebar_nav.rst
- source/community/release_notes/redwood/studio_facelift.rst
Local table of contents should appear in the Redwood product notes pages, matching specs in [wiki](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4247257093/BETA+Course+Search+-+Product+Release+Notes) - I just forgot how to do it initially 😬
> Add local table of contents to Redwood Product Notes

- source/community/release_notes/index.rst
- source/community/release_notes/redwood.rst
- source/community/release_notes/sumac.rst
- source/community/release_notes/sumac/dev_op_release_notes.rst
- source/community/release_notes/sumac/feature_release_notes.rst
As per [mocks from early 2024](https://docs.google.com/presentation/d/1hnot8lO5AmL4biW7UPMvxQVEWEk5-aiVCsqIsvViL3w/edit#slide=id.g2dfcad1c961_0_20), arrange the release notes such that
the differences between the Dev/Operator RNs and the Product or
Feature-based RNs is clear for the current and upcoming releases.
The implementation should match the mock.
Mock ("Teak" should be "Sumac"):
Implemented (see [sandbox](https://docsopenedxorg--531.org.readthedocs.build/en/531/community/release_notes/index.html)):
> docs: Reorganize release notes display

- source/conf.py
More info here: https://about.readthedocs.com/blog/2024/07/addons-by-default/
tl;dr  RTD used to inject data into conf.py but it's going to stop doing
that so we need to read RTD environment variables and pull in that data
ourselves to not break builds.
> build: Deal with RTD Deprecation

- source/community/release_notes/redwood/dev_op_release_notes.rst
Just updating a link since this page currently links to [a wiki page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4247257093/BETA+Course+Search+-+Product+Release+Notes) which then in turn links to the docs.
Preview: https://docsopenedxorg--546.org.readthedocs.build/en/546/community/release_notes/redwood/dev_op_release_notes.html#enabling-studio-course-search
I don't know how to make the link text say "Course Search Beta" instead of "Course Search Beta Release Notes (Redwood)". But that would make this read better.
> docs: course search: link to docs site instead of old wiki

- source/developers/references/developer_guide/conventions/frontend.rst
- source/developers/references/developer_guide/conventions/index.rst
Following up from https://github.com/openedx/open-edx-proposals/pull/616 as suggested by @sarina, to link to it from our Developer Guide.
Preview at:
* https://docsopenedxorg--550.org.readthedocs.build/en/550/developers/references/developer_guide/index.html
* https://docsopenedxorg--550.org.readthedocs.build/en/550/developers/references/developer_guide/conventions/frontend.html
> Link from "Developer Guide" to OEP-67 frontend info

- source/community/release_notes/redwood/dev_op_release_notes.rst
Add a note about the django-social app upgrade for redwood.2 to release notes.
> docs: Add redwood.2 release notes.

- source/developers/quickstarts/index.rst
The Developer Guide is a reference that contains a ton of information about making your first PR, running PR tests, etc. Providing a link to this guide in a "See Also" at the end of the Quickstart index will help route people to the right place for additional digging and info.
Honestly part of the reason I added this is because https://docs.openedx.org/en/latest/developers/quickstarts/index.html looks like an empty page - until I looked ath the rst, I thought it was a blank page
> Add link to Dev Guide within Dev Quickstart for additional info

- source/educators/how-tos/content-tagging-how-tos/index.rst
With `:maxdepth: 0`, subheadings were unexpectedly showing:
However with `:titlesonly:`, only the titles show.
We want this because as the content tagging how-tos grow, this will become a tricky list to navigate. We only want to show the title of each article.
> Use :titlesonly: instead of :maxdepth: 0 on CT How-Tos index

- source/documentors/index.rst
https://docs.openedx.org/en/latest/documentors/
https://docsopenedxorg--571.org.readthedocs.build/en/571/documentors/index.html
> Expose docs concepts articles on documentor's home page

- source/developers/how-tos/enable-translations-new-repo.rst
- source/translators/concepts/translation-process.rst
Docs update after OEP-58 has been implemented. 
See: 
- https://github.com/openedx/open-edx-proposals/pull/610
> docs: update for OEP-58 implementation - FC-55 and FC-12

- source/community/release_notes/redwood/content_tagging.rst
Replace the link to the Open edX wiki to the How-To Create a flat taxonomy by uploading a CSV article on RTD.
@crathbun428 this change is what was meant by the warning box about "backlinking" on this page: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4198924327/How-to+Create+a+flat+taxonomy+by+uploading+a+CSV
> Link Content Tagging How-To in Release Notes

- .github/ISSUE_TEMPLATE/blank-issue.md
- .github/ISSUE_TEMPLATE/config.yml
currently:
wish to make it more like the default:
> Add big blank issue to custom config

- source/educators/concepts/open_edx_platform/index.rst
I think this was just a copy-paste error, but this page has the wrong title:
I retitled it to the best of my ability but would love feedback.
> Update name on Concepts index page

- source/community/release_notes/named_release_branches_and_tags.rst
Redwood.3 release update. This points latest release to Redwood.
See: https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#4b.-Make-the-new-release-notes-the-%E2%80%9Clatest%E2%80%9D
> chore: update docs for new Redwood.3 release

- source/documentors/references/doc_english_writing.rst
This PR migrates the Guidelines for writing global English from a past edx documentation repository that will be deprecated.
> FC-0068 docs: migrate guidelines for writing

- source/conf.py
- source/developers/concepts/hooks_extension_framework.rst
- source/developers/index.rst
This PR adds documentation about the Hooks Extension Framework under the developers section to centralize common concepts between Open edX Events and filters, such as framework overview, differences, comparisons, etc.
You can see the docs rendered here: https://docsopenedxorg--599.org.readthedocs.build/en/599/developers/concepts/index.html
The documentation in https://github.com/openedx/edx-platform/tree/master/docs/hooks should be removed after this gets merged. What this docs is missing from edx-platform guides, it's the index of filters and events within edx-platform:
https://github.com/openedx/edx-platform/blob/master/docs/hooks/filters.rst#index-of-filters
https://github.com/openedx/edx-platform/blob/master/docs/hooks/events.rst#index-of-events
This PR will not replace those indexes …
> docs: [FC-0074] centralize docs for the hooks extension framework

- source/developers/concepts/hooks_extension_framework.rst
This PR clarifies what standard the hooks extension framework offers to extension developers, addressing this comment: https://github.com/openedx/docs.openedx.org/pull/599#discussion_r1828353125
> docs: [FC-0074] improve wording in standard that offers framework

- source/developers/concepts/hooks_extension_framework.rst
This PR adds a few follow-up questions to decide whether to use an event or a filter. This is only a proposal to clarify even more which hook to use, so if you think this is redundant, then I'm okay with closing this PR.
> docs: [FC-0074] add follow-up questions to decide which type of hook to use

- source/documentors/concepts/content_types.rst
This PR adds the diataxis criteria documentation approved.
Google doc: https://docs.google.com/document/d/1mHnd2mJTy-IAgGxE0sP6AO0_oNogQbXhEQNZtzigLww/edit?tab=t.0#heading=h.lpo0vmwalr3v
Rendered page: https://docsopenedxorg--612.org.readthedocs.build/en/612/documentors/concepts/content_types.html
> FC-0068 docs: diataxis criteria documentation

- source/documentors/references/quick_reference_rst.rst
This PR adds the references from the past Templates page to the quick reference RST page to avoid losing import information while adding the new content.
> FC-0068 docs: update quick reference RST content

- source/developers/references/glossary.rst
This PR erase the edX reference in the glossary that belong to the developers section.
> fix: erase edx reference in the glossary

- source/community/release_notes/redwood/content_tagging.rst
Currently the codeblock syntax is wrong resulting in non-rendering of tag hierarchy example:
Fixed:
> Fix codeblock syntax in Redwood tagging notes

- source/educators/references/course_development/exercise_tools/dropdown_problem_xml.rst
- source/educators/references/course_development/exercise_tools/external_grader_requirements.rst
- source/educators/references/course_development/exercise_tools/gene_explorer.rst
- source/educators/references/course_development/exercise_tools/image_mapped_input_xml.rst
- source/educators/references/course_development/exercise_tools/lti_component.rst
- source/educators/references/course_development/exercise_tools/lti_component_settings.rst
- source/educators/references/course_development/exercise_tools/math_expression_input.rst
- source/educators/references/course_development/exercise_tools/math_expression_input_xml.rst
- source/educators/references/course_development/exercise_tools/multi_select.rst
- source/educators/references/course_development/exercise_tools/multi_select_xml.rst
This PR corrects simple RST standard errors in some educator documentation references and erases one edX reference.
> FC-0068 docs: Reference cleaning by edunext #3

- source/educators/how-tos/advanced_features/lti_blackboard_example.rst
- source/educators/how-tos/advanced_features/lti_canvas_example.rst
- source/educators/navigation/advanced_features.rst
- source/educators/references/course_development/Section_adding_tooltip.rst
- source/educators/references/course_development/Section_partial_credit.rst
- source/educators/references/course_development/advanced_problem_editor.rst
- source/educators/references/course_development/exercise_tools/Section_adding_hints.rst
- source/educators/references/course_development/exercise_tools/drag_and_drop.rst
- source/educators/references/course_development/exercise_tools/numerical_input.rst
- source/educators/references/course_development/exercise_tools/numerical_input_xml.rst
This PR modifies a series of reference documents migrated from the legacy repositories to the educators' documentation. The principal changes in the lti_canvas_example and lti_blackboard_example were converted into how-tos. An issue will be created for each document for an extended review.
In the case of drag_and_drop and numerical_input, there is one reference to edX legacy repositories in each document that I could not erase or replace with another link.
> FC-0068: Reference cleaning by edunext #4

- source/developers/references/developer_guide/process/code-considerations.rst
- source/developers/references/developer_guide/process/overview.rst
- source/educators/concepts/accessibility/accessibility_guidelines.rst
- source/educators/concepts/accessibility/best_practices_course_content_dev.rst
- source/educators/concepts/accessibility/design_for_mobile.rst
- source/educators/concepts/accessibility/supporting_learners_diverse_needs.rst
- source/links.txt
Adjust docs related to accessibility to make them relevant to Open edX. Involved:
- Changing edx.org references
- Replacing edx.org-specific support (e.g. accessibility@edx.org) with Open edX community support (e.g. github issues)
- Replace edx.org-specific legalese that we should not adopt.
> Modify Accessibility guidelines from legacy to Open edX

- source/educators/how-tos/advanced_features/add_cohorts.rst
- source/educators/how-tos/advanced_features/assign_learners_cohort_csv.rst
- source/educators/how-tos/advanced_features/assign_learners_cohort_manually.rst
- source/educators/how-tos/advanced_features/chage_learner_cohort_assignment.rst
- source/educators/how-tos/advanced_features/change_assignment_method_cohort.rst
- source/educators/how-tos/advanced_features/disable_cohorts.rst
- source/educators/how-tos/advanced_features/enable_cohorts.rst
- source/educators/how-tos/advanced_features/managing_cohorts.rst
- source/educators/how-tos/advanced_features/rename_cohort.rst
- source/educators/how-tos/course_development/add_course_live.rst
- source/educators/how-tos/course_development/export_import_library.rst
- source/educators/navigation/advanced_features.rst
- source/educators/references/glossary.rst
This PR modifies a series of how-to documents migrated from the legacy repositories to the educators' documentation. Also creates some how-tos from the managing_cohorts document and modifies the Glossary from educators.
> FC-0068 docs: How-to cleaning by edunext #9

- source/educators/how-tos/course_development/text_components/add_link_website_unit_file.rst
- source/educators/how-tos/preview_content.rst
- source/educators/how-tos/view_published_released_content.rst
- source/educators/navigation/content_creation_management.rst
- source/educators/references/course_development/about_video_guidelines.rst
- source/educators/references/course_development/add_video_to_course.rst
- source/educators/references/course_development/course_export_terminology.rst
- source/educators/references/course_development/exercise_tools/SCORM_overview.rst
- source/educators/references/course_development/exercise_tools/conditional_module.rst
- source/educators/references/course_development/exercise_tools/google_docs.rst
- source/educators/references/course_development/exercise_tools/mathjax_studio.rst
- source/educators/references/course_development/exercise_tools/text_input.rst
- source/educators/references/course_development/exercise_tools/text_input_xml.rst
- source/educators/references/course_development/files_page.rst
- source/educators/references/course_development/parent_child_components.rst
- source/educators/references/course_development/troubleshoot_video.rst
- source/educators/references/course_development/work_with_targz_file.rst
- source/educators/references/testing_course_content.rst
This PR modifies a series of reference documents migrated from the legacy repositories to the educators' documentation.
The principal changes are in the add_link_website_unit_file, which was modified to be a how-to and create two how-tos based on testing_course_content.
In this PR, some articles maintain links that direct to edX legacy repositories, as the content has not been migrated to Open edX repositories.
> FC-0068 docs: Reference cleaning by edunext #7

- source/educators/how-tos/add_content_iframe.rst
- source/educators/how-tos/add_course_creators.rst
- source/educators/how-tos/course_development/set_course_highlights.rst
- source/educators/how-tos/set_licensing.rst
- source/educators/how-tos/share_courses_social_media.rst
- source/educators/how-tos/update_course_specific_settings.rst
- source/educators/how-tos/view_another_learners_profile.rst
- source/educators/navigation/creating_course.rst
- source/educators/references/course_pacing.rst
- source/educators/references/resources_for_course_teams.rst
- source/educators/references/roles_for_viewing.rst
- source/educators/references/scheduling_course.rst
- source/educators/references/setting_course_pacing.rst
adding see also table for roles_for_viewing.rst
> adding see also tables

- source/educators/concepts/advanced_features/cohorts_overview.rst
- source/educators/concepts/advanced_features/timed_exams.rst
- source/educators/concepts/exercise_tools/peer_instruction.rst
- source/educators/concepts/exercise_tools/randomized_content.rst
- source/educators/concepts/exercise_tools/single_select_overview.rst
- source/educators/concepts/exercise_tools/staff_graded.rst
- source/educators/how-tos/course_development/Subsection_configure_hints.rst
- source/educators/how-tos/course_development/exercise_tools/add_hints_advanced_editor.rst
- source/educators/how-tos/course_development/exercise_tools/add_peer_instruction_tool.rst
- source/educators/how-tos/course_development/exercise_tools/create_periodic_table.rst
This PR modifies some how-tos and concept documents migrated from the legacy repositories to the educators' documentation.
> FC-0068 docs: concept and how-tos cleaning by edunext 13

- source/educators/how-tos/course_development/exercise_tools/create_problem_in_latex.rst
- source/educators/how-tos/course_development/exercise_tools/create_problem_with_hint.rst
- source/educators/how-tos/course_development/exercise_tools/create_protein_builder.rst
- source/educators/how-tos/proctored_exams/allow_opt_out_proctored_exam.rst
- source/educators/how-tos/proctored_exams/create_proctored_exam_pt.rst
- source/educators/how-tos/proctored_exams/create_proctored_exam_rpnow.rst
- source/educators/how-tos/proctored_exams/enable_proctored_exams.rst
- source/educators/how-tos/proctored_exams/manage_proctored_exams.rst
- source/educators/how-tos/proctored_exams/review_pt_results.rst
- source/educators/how-tos/proctored_exams/review_rpnow_results.rst
This PR modifies a series of how-to documents migrated from the legacy repositories to the educators' documentation.
The updated files were:
- `create_problem_in_latex.rst`
- `create_problem_with_hint.rst`
- `create_protein_builder.rst`
- `allow_opt_out_proctored_exam.rst`
- `create_proctored_exam_pt.rst`
- `create_proctored_exam_rpnow.rst`
- `enable_proctored_exams.rst`
- `manage_proctored_exams.rst`
- `review_pt_results.rst`
- `review_rpnow_results.rst`
> FC-0068 docs: how-to cleaning by edunext #18

- source/educators/concepts/advanced_features/lti_reuse_content.rst
- source/educators/concepts/advanced_features/managing_teams_discussions.rst
- source/educators/concepts/advanced_features/teams_learner_experience.rst
- source/educators/concepts/advanced_features/teams_overview.rst
- source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
- source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
- source/educators/concepts/exercise_tools/create_exercises.rst
- source/educators/concepts/exercise_tools/drag_and_drop.rst
- source/educators/concepts/exercise_tools/external_graders.rst
- source/links.txt
This PR modifies a series of concept documents migrated from the legacy repositories to the educators' documentation.
> FC-0068 docs: concept cleaning by edunext #11

- source/site_ops/how-tos/configuring-site-wide-analytics-tools.rst
This PR aims to help add documentation regarding adding analytics to the platform apart from Google Analytics.
Useful information to include:
Nothing to test
"None"
Include anything else that will help reviewers and consumers understand the change.
Private ref: [BB-9388](https://tasks.opencraft.com/browse/BB-9388)
> chore: Add matamo integration doc

- source/developers/concepts/hooks_extension_framework.rst
Fixes https://readthedocs.org/projects/docsopenedxorg/builds/26859007/
> docs: update references of events with latest documentation

- source/educators/how-tos/add_dropdown.rst
- source/educators/how-tos/add_multiple_choice.rst
- source/educators/how-tos/course_development/exercise_tools/add_recommenderXBlock.rst
- source/educators/how-tos/course_development/exercise_tools/add_single_select.rst
- source/educators/how-tos/course_development/exercise_tools/add_single_select_num_input.rst
- source/educators/how-tos/course_development/exercise_tools/award_partial_credit_multiple_choice.rst
- source/educators/how-tos/course_development/exercise_tools/edit_single_select_advanced.rst
- source/educators/how-tos/course_development/exercise_tools/use_randomized_content_blocks.rst
This PR modifies a series of how-to documents migrated from the legacy repositories to the educators' documentation.
The updated files were:
- `add_dropdown.rst`
- `add_multiple_choice.rst`
- `add_recommenderXBlock.rst`
- `add_single_select.rst`
- `add_single_select_num_input.rst`
- `award_partial_credit_multiple_choice.rst`
- `edit_single_select_advanced.rst`
- `use_randomized_content_blocks.rst`
> FC-0068 docs: how-to cleaning by edunext #19

- source/educators/how-tos/add_update_full_profile.rst
- source/educators/how-tos/content-tagging-how-tos/add_delete_tags_course_content.rst
- source/educators/how-tos/content-tagging-how-tos/build_taxonomy_using_template.rst
- source/educators/how-tos/content-tagging-how-tos/export_tag_data_from_course.rst
- source/educators/how-tos/content-tagging-how-tos/manage_permissions_taxonomy.rst
- source/educators/how-tos/content-tagging-how-tos/update_reimport_taxonomy.rst
- source/educators/how-tos/course_development/exercise_tools/add_calculator.rst
- source/educators/how-tos/update_rerun_course.rst
- source/educators/how-tos/use_section_independently_of_course_outline.rst
- source/educators/references/resources_for_course_teams.rst
* Fixes `:ref:` links that had spaces, which broke the reference
* Adds targets to titles in various files, so we can use the `:ref:` directive
* Remove duplicate reference links
* Adjusts headings
> Fix seealso tables and :ref: links

- source/community/release_notes/juniper.rst
- source/community/release_notes/koa.rst
- source/community/release_notes/lilac.rst
- source/community/release_notes/maple.rst
- source/community/release_notes/nutmeg.rst
- source/community/release_notes/olive.rst
- source/community/release_notes/palm.rst
- source/community/release_notes/redwood/dev_op_release_notes.rst
- source/developers/references/developer_guide/index.rst
- source/educators/references/resources_for_course_teams.rst
- source/links.txt
* Fix some outdated ref links
* Swap links to edx.rtd/edx-platform-technical to docs.openedx.org links
* Swap links to edx.rtd/named-releases to docs.openedx.org links
* Swap some edx.rtd links with docs.openedx.org links
> Fix some outdated ref links

- Makefile
Proposal to make the --keep-going flag the default, so that the build process does not exit on the first error.
> Default build to use --keep-going flag

- requirements/base.in
- requirements/base.txt
- requirements/pip.txt
- source/conf.py
Adds a nicer 404 page to our docs
Rather than a generic 404 page without nav context, https://docs.openedx.org/en/latest/community/release_notes/verawood.html
See https://docsopenedxorg--850.org.readthedocs.build/en/850/community/release_notes/verawood.html
> build: Add sphinx-notfound-page extension

- source/community/release_notes/ironwood.rst
- source/community/release_notes/juniper_learner.rst
- source/community/release_notes/lilac.rst
- source/community/release_notes/palm.rst
- source/community/release_notes/palm/ora_improvements.rst
- source/developers/references/developer_guide/process/code-considerations.rst
- source/developers/references/developer_guide/process/contributor.rst
- source/developers/references/developer_guide/process/overview.rst
- source/documentors/decisions/0001-purpose-of-this-repo.rst
- source/educators/references/course_development/awarding_partial_credit.rst
- source/educators/references/course_development/parent_child_components.rst
- source/educators/references/data/student_profile_report.rst
- source/links.txt
Convert links from edx.readthedocs.io to links on docs.openedx.org
The installing & configuring guide is not yet moved, so those links are currently unchanged. Ref https://github.com/openedx/docs.openedx.org/issues/830
> Update or remove outdated/broken links

- source/educators/concepts/exercise_tools/about_lti_component.rst
This PR updates the about_lti_component.
Details of changes:
- Improve the intro paragraph.
- Remove the duplicated accessibility note.
- Improve the overview description.
- Remove the tool consumer and tool provider explanation because they are platform and tool right now, and I don't think that info should be necessary for this concept page. Reference: https://www.imsglobal.org/spec/lti/v1p3#platforms-and-tools
- Conver to a note of the bits of information.
- Remove an outdated comment.
- Move the reference of Using Open edX as an LTI Tool Provider to the See also section.
- Complete the maintenance chart
https://docsopenedxorg--960.org.readthedocs.build/en/960/educators/concepts/exercise_tools/about_lti_component.html
1. If the document is a **how-to** or **quickstart**, complete the …
> docs: Update the about_lti_component doc

- source/educators/how-tos/course_development/exercise_tools/enable_lti_component.rst
I only improved the format of the how-to and added more details.
https://docsopenedxorg--961.org.readthedocs.build/en/961/educators/how-tos/course_development/exercise_tools/enable_lti_component.html
1. If the document is a **how-to** or **quickstart**, complete the steps as instructed and confirm that the outcome in your Open edX instance is the same as what the doc expects.
2. If the document is a **reference**, confirm that the reference is complete and matches what you observe in your current Open edX version.
3. If the document is a **concept**, confirm that the information is accurate and up-to-date
Rendered https://docsopenedxorg--961.org.readthedocs.build/en/961/educators/how-tos/course_development/exercise_tools/enable_lti_component.html
> docs: update the enable_lti_component doc

- .readthedocs.yaml
- source/community/release_notes/juniper.rst
- source/developers/references/developer_guide/index.rst
Configure search results
- Deprioritize old release pages (Juniper is always a high result for me)
- Priviledge quickstarts
- Bring up Developer's Guide which is currently very low every time I search for it.
https://docs.readthedocs.com/platform/stable/config-file/v2.html#search-ranking
> Configure search result optimizations

- source/maintenance_chart_checker.py
Script provides the ability to generate reports on maintenance chart empty/pass/fail coverage: 
You can specify a particular directory:
And/or the levels of directories to group your report by:
> feat: Add script for reporting maintenance chart pass/fail coverage

- source/site_ops/references/frontend-plugin-slots.rst
https://docsopenedxorg--1065.org.readthedocs.build/en/1065/site_ops/references/frontend-plugin-slots.html
Related:
* https://github.com/openedx/public-engineering/issues/352
* https://github.com/openedx/frontend-plugin-framework/pull/99
> docs: update frontend plugin slots reference for teak

- source/community/how-tos/read_the_roadmap.rst
- source/community/release_notes/redwood/aspects.rst
- source/community/release_notes/redwood/dev_op_release_notes.rst
- source/community/release_notes/sumac/aspects_comp_dashboard.rst
- source/community/release_notes/sumac/dev_op_release_notes.rst
- source/developers/references/aspects_home.rst
- source/site_ops/install_configure_run_guide/analytics/index.rst
This is part of a greater docs cleanup.
Usage of `:doc:` is an antipattern. It is fragile and prone to breaking cross references when docs are moved or renamed.
Replace with usages of `:ref:`. Depends on https://github.com/openedx/openedx-aspects/pull/328
> chore: Add Aspects references to docs to make relative, not direct, references

- requirements/base.txt
- requirements/constraints.txt
requirements/constraints.txt specifies an issue that was blocking the Sphinx upgrade. That issue is now closed!
I tested this locally by viewing pages with the following:
* Intersphinx references
* Local cross references
* External links
* Images
* Emoji
* Video
* Diagrams
> chore: Upgrade Sphinx to 8.2.3

- source/community/release_notes/maple.rst
- source/developers/concepts/hooks_extension_framework.rst
- source/developers/how-tos/enable-translations-new-repo.rst
- source/developers/how-tos/get-ready-for-python-dev.rst
- source/developers/maintainers_home.rst
- source/developers/references/developer_guide/process/code-considerations.rst
- source/developers/references/developer_guide/process/landing-your-work.rst
- source/developers/references/developer_guide/process/using-git.rst
- source/developers/references/developer_guide/testing/github-actions.rst
- source/developers/references/running_pr_tests.rst
Usage of `:doc:` is an antipattern. It is fragile and prone to breaking cross references when docs are moved or renamed.
Adding in `.. _reference:` syntax to files and headings means cross-references can instead be made with the `:ref:` directive, which will (presuming the references themselves are not deleted or renamed) be more robust to docs refactorings.
Depends on https://github.com/openedx/open-edx-proposals/pull/716
> chore: Update OEP :doc: directives to :ref:s

- source/community/release_notes/teak/teak_frontend_plugin_slots.rst
Adding descriptions for the pending plugin slots from authoring and learning mfe's.
Since we already created some docs for some plugins slots on their own repos,  this should be reflected on the global docs for openEdx.
* https://github.com/openedx/frontend-app-learning/pull/1770 
* https://github.com/openedx/frontend-app-authoring/pull/2315
* https://github.com/openedx/frontend-app-authoring/pull/2321
> Adding description for pending frontend plugin slots

- source/community/release_notes/teak.rst
- source/community/release_notes/teak/feature_release_notes.rst
- source/community/release_notes/teak/smaller_changes.rst
- source/community/release_notes/teak/teak_marketing_notes.rst
- source/index.rst
Adding product marketing release notes for Teak to the docs site (alt version - version 1 in #1276 ) - agreed upon in Slack.
https://docsopenedxorg--1287.org.readthedocs.build/en/1287/community/release_notes/teak/teak_marketing_notes.html#teak-product-marketing-notes
> Draft Product Marketing release notes (alt)
